resolver:
  compiler: ghc-8.0.1

extra-deps:
# from Debian Stretch:
- alex-3.1.7
- cabal-install-1.24.0.1
# haddock
- happy-1.19.5
- hscolour-1.24.1
# stack

- async-2.1.0
- attoparsec-0.13.1.0
- case-insensitive-1.2.0.7
- fgl-5.5.3.0
- fixed-0.2.1.1
- GLURaw-2.0.0.2
- GLUT-2.7.0.10
- half-0.2.2.3
- hashable-1.2.4.0
- haskell-src-1.0.2.0
- html-1.0.1.2
- HTTP-4000.3.3
- HUnit-1.3.1.2
# integer-logarithms?
- mtl-2.2.1
- network-2.6.3.1
- network-uri-2.6.1.0
- ObjectName-1.1.0.1
- OpenGL-3.0.1.0
- OpenGLRaw-3.2.3.0
- parallel-3.2.1.0
- parsec-3.1.11
- primitive-0.6.1.0
- QuickCheck-2.8.2
- random-1.1
- regex-base-0.93.2
- regex-compat-0.95.1
- regex-posix-0.95.2
- scientific-0.3.4.9
- split-0.2.3.1
- StateVar-1.1.0.4
- stm-2.4.4.1
- syb-0.6
- text-1.2.2.1
- tf-random-0.5
# transformers?
- unordered-containers-0.2.7.1
- vector-0.11.0.0
# xhtml?
- zlib-0.6.1.2

# Override default flag values for local packages and extra-deps
# flags: {}

# Extra package databases containing global packages
# extra-package-dbs: []
